Repository stacks-sbtc/sbtc, pull requests merged in 2025-04, with the labels that each got.

#1575 chore(ci): add pull_request trigger to on-push workflow
  .github/workflows/on-push.yaml
Labels: CI

#1582 chore: bump rust to 1.86.0
  .github/actions/dockerfiles/Dockerfile.blocklist-client.debian
  .github/actions/dockerfiles/Dockerfile.signer.debian
  README.md
  docker/sbtc/Dockerfile
  emily/handler/src/api/handlers/internal.rs
  rust-toolchain.toml
  sbtc/src/idpack/segmenters/bitmap.rs
  signer/src/bitcoin/packaging.rs
  signer/src/bitcoin/utxo.rs
Labels: chore

#1559 feat: signers no longer store transactions in the database
  signer/migrations/0015__drop_transactions_tx_column.sql
  signer/src/bitcoin/utxo.rs
  signer/src/block_observer.rs
  signer/src/storage/in_memory.rs
  signer/src/storage/mod.rs
  signer/src/storage/model.rs
  signer/src/storage/postgres.rs
  signer/src/storage/sqlx.rs
  signer/src/testing/dummy.rs
  signer/src/testing/request_decider.rs
  signer/src/testing/storage/model.rs
  signer/src/testing/transaction_coordinator.rs
  signer/src/testing/wsts.rs
  signer/src/transaction_coordinator.rs
  signer/tests/integration/block_observer.rs
  signer/tests/integration/postgres.rs
  signer/tests/integration/rotate_keys.rs
  signer/tests/integration/setup.rs
  signer/tests/integration/transaction_coordinator.rs
Labels: sbtc signer binary

#1560 refactor: simplify deposit request processing in block the observer
  signer/src/block_observer.rs
  signer/src/metrics.rs
Labels: sbtc signer binary

#1587 chore(ci): fix double CI-runs between PR and push
  .github/workflows/on-push.yaml
Labels: CI

#1568 feat: introduce p2p connection limiting (`#1547`)
  signer/src/context/messaging.rs
  signer/src/context/signer_state.rs
  signer/src/lib.rs
  signer/src/main.rs
  signer/src/network/libp2p/bootstrap.rs
  signer/src/network/libp2p/errors.rs
  signer/src/network/libp2p/event_loop.rs
  signer/src/network/libp2p/swarm.rs
  signer/tests/integration/communication.rs
  supply-chain/config.toml
  supply-chain/imports.lock
Labels: sbtc signer binary, signer communication

#1581 Push release Docker images to GHCR instead of DockerHub
  .github/actions/dockerfiles/Dockerfile.blocklist-client.debian
  .github/actions/dockerfiles/Dockerfile.signer.debian
  .github/workflows/image-build-and-draft-release.yaml
Labels: CI

#1580 fix: `cargo clippy --all-targets` (partial)
  blocklist-client/src/client/risk_client.rs
  emily/handler/src/api/handlers/deposit.rs
  emily/handler/src/api/handlers/new_block.rs
  emily/handler/tests/integration/common.rs
  emily/handler/tests/integration/deposit.rs
  emily/handler/tests/integration/limits.rs
  emily/handler/tests/integration/new_block.rs
  emily/handler/tests/integration/withdrawal.rs
  sbtc/src/deposits.rs
  sbtc/src/events.rs
  sbtc/src/idpack/tests.rs
  sbtc/tests/integration/validation.rs
  signer/src/bitcoin/utxo.rs
  signer/src/storage/in_memory.rs
  signer/tests/integration/bitcoin_validation.rs
  signer/tests/integration/emily.rs
  signer/tests/integration/rotate_keys.rs
  signer/tests/integration/transaction_coordinator.rs
Labels: chore

#1599 feat: write stacks block hash with key rotation events
  sbtc/src/events.rs
  signer/migrations/0016__add_block_hash_rotate_keys_events.sql
  signer/src/api/new_block.rs
  signer/src/stacks/wallet.rs
  signer/src/storage/in_memory.rs
  signer/src/storage/mod.rs
  signer/src/storage/model.rs
  signer/src/storage/postgres.rs
  signer/src/testing/dummy.rs
  signer/src/testing/wsts.rs
  signer/tests/integration/block_observer.rs
  signer/tests/integration/rotate_keys.rs
Labels: sbtc signer binary

#1624 [feat] add fund-btc command to signers.sh
  signers.sh
Labels: enhancement

#1601 feat: drop stacks transactions and transactions tables
  signer/migrations/0017__remove_stacks_transactions_table.sql
  signer/src/api/new_block.rs
  signer/src/block_observer.rs
  signer/src/stacks/wallet.rs
  signer/src/storage/in_memory.rs
  signer/src/storage/mod.rs
  signer/src/storage/model.rs
  signer/src/storage/postgres.rs
  signer/src/testing/dummy.rs
  signer/src/testing/storage/model.rs
  signer/src/testing/wsts.rs
  signer/tests/integration/block_observer.rs
  signer/tests/integration/contracts.rs
  signer/tests/integration/emily.rs
  signer/tests/integration/postgres.rs
  signer/tests/integration/rotate_keys.rs
  signer/tests/integration/setup.rs
  signer/tests/integration/transaction_coordinator.rs
Labels: sbtc signer binary, breaking-local

#1604 feat: fetch stacks block headers instead of the blocks
  signer/src/block_observer.rs
  signer/src/stacks/api.rs
Labels: sbtc signer binary

#1627 chore: clean-up logging in Emily v1
  emily/handler/src/api/handlers/internal.rs
  emily/handler/src/common/error.rs
  emily/handler/src/context.rs
  emily/handler/src/database/accessors.rs
  emily/handler/src/database/entries/deposit.rs
  emily/handler/src/database/entries/mod.rs
  emily/handler/src/database/entries/withdrawal.rs
Labels: chore
